import { Compound, LabMarker } from '../types';

export const CATEGORY_LABELS: Record<string, { label: string; iconName: string; badgeColor: string }> = {
  steroid: {
    label: 'Esteroides & TRT',
    iconName: 'Syringe',
    badgeColor: 'bg-blue-950/70 text-blue-300 border-blue-800/50',
  },
  peptide: {
    label: 'Peptídeos & GLP-1',
    iconName: 'Sparkles',
    badgeColor: 'bg-emerald-950/70 text-emerald-300 border-emerald-800/50',
  },
  estrogen: {
    label: 'Hormônios Femininos / HRT',
    iconName: 'Heart',
    badgeColor: 'bg-pink-950/70 text-pink-300 border-pink-800/50',
  },
  fertility: {
    label: 'Fertilidade, TPC & Protetores',
    iconName: 'Shield',
    badgeColor: 'bg-amber-950/70 text-amber-300 border-amber-800/50',
  },
  other: {
    label: 'Outros Compostos',
    iconName: 'Activity',
    badgeColor: 'bg-slate-800 text-slate-300 border-slate-700',
  },
};

export const DEFAULT_COMPOUNDS: Compound[] = [
  // =========================================================================
  // 1. ESTEROIDES ANABOLIZANTES & ANDROGÊNICOS (TRT & AAS)
  // =========================================================================
  {
    id: 'test_cypionate',
    name: 'Cipionato de Testosterona (Deposteron)',
    category: 'steroid',
    subcategory: 'Testosterona',
    halfLifeDays: 8.0,
    peakHours: 36,
    defaultConcentrationMgMl: 200,
    color: '#3b82f6',
    unit: 'mg',
    bioavailability: 1.0,
    description: 'Éster longo padrão ouro em TRT no Brasil e EUA. Meia-vida de ~8 dias.',
    standardReferenceRange: { min: 300, max: 900, unit: 'ng/dL' },
  },
  {
    id: 'test_enanthate',
    name: 'Enantato de Testosterona',
    category: 'steroid',
    subcategory: 'Testosterona',
    halfLifeDays: 4.5,
    peakHours: 28,
    defaultConcentrationMgMl: 250,
    color: '#0ea5e9',
    unit: 'mg',
    bioavailability: 1.0,
    description: 'Éster médio (~4.5 a 5 dias). Níveis muito estáveis com 2 aplicações semanais.',
    standardReferenceRange: { min: 300, max: 900, unit: 'ng/dL' },
  },
  {
    id: 'test_propionate',
    name: 'Propionato de Testosterona',
    category: 'steroid',
    subcategory: 'Testosterona',
    halfLifeDays: 1.5,
    peakHours: 14,
    defaultConcentrationMgMl: 100,
    color: '#06b6d4',
    unit: 'mg',
    bioavailability: 1.0,
    description: 'Éster de ação curta (~1.5 dias de meia-vida). Exige aplicações diárias ou DSDN.',
    standardReferenceRange: { min: 300, max: 900, unit: 'ng/dL' },
  },
  {
    id: 'sustanon_blend',
    name: 'Durateston / Sustanon 250 (Blend 4 Ésteres)',
    category: 'steroid',
    subcategory: 'Testosterona',
    halfLifeDays: 6.5,
    peakHours: 24,
    defaultConcentrationMgMl: 250,
    color: '#8b5cf6',
    unit: 'mg',
    bioavailability: 1.0,
    description: 'Mix de Propionato, Fenilpropionato, Isocaproato e Decanoato.',
    standardReferenceRange: { min: 300, max: 900, unit: 'ng/dL' },
  },
  {
    id: 'test_undecanoate',
    name: 'Undecanoato de Testosterona (Nebido)',
    category: 'steroid',
    subcategory: 'Testosterona',
    halfLifeDays: 24.0,
    peakHours: 168,
    defaultConcentrationMgMl: 250,
    color: '#6366f1',
    unit: 'mg',
    bioavailability: 1.0,
    description: 'Éster ultra-longo em óleo de rícino com meia-vida prolongada (~24-30 dias).',
    standardReferenceRange: { min: 300, max: 900, unit: 'ng/dL' },
  },
  {
    id: 'test_suspension',
    name: 'Testosterona Base / Suspensão Aquosa',
    category: 'steroid',
    subcategory: 'Testosterona',
    halfLifeDays: 0.5,
    peakHours: 3,
    defaultConcentrationMgMl: 100,
    color: '#38bdf8',
    unit: 'mg',
    bioavailability: 1.0,
    description: 'Testosterona pura não esterificada em água. Pico quase imediato (3h) e meia-vida ultracurta.',
  },

  // 19-Nor (Nandrolonas & Trembolonas)
  {
    id: 'nandrolone_decanoate',
    name: 'Decanoato de Nandrolona (Deca-Durabolin)',
    category: 'steroid',
    subcategory: '19-Nor',
    halfLifeDays: 8.5,
    peakHours: 40,
    defaultConcentrationMgMl: 200,
    color: '#eab308',
    unit: 'mg',
    bioavailability: 1.0,
    description: '19-nor-testosterona com ação anabólica potente e alívio articular com meia-vida de 8.5 dias.',
  },
  {
    id: 'nandrolone_phenylpropionate',
    name: 'Fenilpropionato de Nandrolona (NPP)',
    category: 'steroid',
    subcategory: '19-Nor',
    halfLifeDays: 2.7,
    peakHours: 18,
    defaultConcentrationMgMl: 100,
    color: '#facc15',
    unit: 'mg',
    bioavailability: 1.0,
    description: 'Versão rápida da Deca com meia-vida de 2.7 dias, permitindo controle mais rápido de colaterais.',
  },
  {
    id: 'trenbolone_acetate',
    name: 'Acetato de Trembolona',
    category: 'steroid',
    subcategory: '19-Nor',
    halfLifeDays: 1.5,
    peakHours: 12,
    defaultConcentrationMgMl: 100,
    color: '#ef4444',
    unit: 'mg',
    bioavailability: 1.0,
    description: 'Composto extremamente androgênico e anabólico. Meia-vida curta (~1.5 dias).',
  },
  {
    id: 'trenbolone_enanthate',
    name: 'Enantato de Trembolona',
    category: 'steroid',
    subcategory: '19-Nor',
    halfLifeDays: 5.5,
    peakHours: 36,
    defaultConcentrationMgMl: 200,
    color: '#dc2626',
    unit: 'mg',
    bioavailability: 1.0,
    description: 'Éster longo de trembolona com meia-vida de ~5.5 dias.',
  },

  // Derivados de DHT
  {
    id: 'primobolan_enanthate',
    name: 'Enantato de Metenolona (Primobolan Depot)',
    category: 'steroid',
    subcategory: 'Derivado DHT',
    halfLifeDays: 5.0,
    peakHours: 30,
    defaultConcentrationMgMl: 100,
    color: '#84cc16',
    unit: 'mg',
    bioavailability: 1.0,
    description: 'Derivado de DHT refinado, sem conversão em estrogênio, excelente perfil de segurança e composição.',
  },
  {
    id: 'drostanolone_propionate',
    name: 'Propionato de Drostanolona (Masteron)',
    category: 'steroid',
    subcategory: 'Derivado DHT',
    halfLifeDays: 1.5,
    peakHours: 12,
    defaultConcentrationMgMl: 100,
    color: '#10b981',
    unit: 'mg',
    bioavailability: 1.0,
    description: 'Derivado de DHT com efeito anti-estrogênico e densidade muscular. Meia-vida de 1.5 dias.',
  },
  {
    id: 'drostanolone_enanthate',
    name: 'Enantato de Drostanolona (Masteron Enan)',
    category: 'steroid',
    subcategory: 'Derivado DHT',
    halfLifeDays: 5.0,
    peakHours: 32,
    defaultConcentrationMgMl: 200,
    color: '#059669',
    unit: 'mg',
    bioavailability: 1.0,
    description: 'Versão de ação longa do Masteron para aplicações 2x por semana.',
  },
  {
    id: 'boldenone_undecylenate',
    name: 'Undecilenato de Boldenona (Equipoise)',
    category: 'steroid',
    subcategory: 'Derivado Testosterona',
    halfLifeDays: 14.0,
    peakHours: 96,
    defaultConcentrationMgMl: 250,
    color: '#f97316',
    unit: 'mg',
    bioavailability: 1.0,
    description: 'Éster muito longo de boldenona (~14 dias de meia-vida), apetite e vascularização.',
  },
  {
    id: 'oxandrolone',
    name: 'Oxandrolona (Anavar Oral)',
    category: 'steroid',
    subcategory: 'Oral / Derivado DHT',
    halfLifeDays: 0.42, // ~10 horas
    peakHours: 2,
    defaultConcentrationMgMl: 20,
    color: '#fbbf24',
    unit: 'mg',
    bioavailability: 0.95,
    description: 'Oral suave, alta taxa anabólica com baixíssima androgenicidade. Meia-vida de 9-10 horas.',
  },
  {
    id: 'stanozolol_inj',
    name: 'Estanozolol Injetável (Winstrol Depot)',
    category: 'steroid',
    subcategory: 'Derivado DHT',
    halfLifeDays: 1.0,
    peakHours: 8,
    defaultConcentrationMgMl: 50,
    color: '#a3e635',
    unit: 'mg',
    bioavailability: 1.0,
    description: 'Suspensão aquosa de estanozolol com meia-vida de cerca de 24 horas.',
  },
  {
    id: 'rip_cut_blend',
    name: 'Rip / Cut Blend (Propionato + Masteron + Trembo Acetato)',
    category: 'steroid',
    subcategory: 'Blend Combinado (Definição)',
    halfLifeDays: 1.5,
    peakHours: 12,
    defaultConcentrationMgMl: 150,
    color: '#f43f5e',
    unit: 'mg',
    bioavailability: 1.0,
    description: 'Blend sinérgico de 3 compostos de ésteres curtos para máxima definição, densidade e vascularização.',
    enabled: false,
  },

  // =========================================================================
  // 2. PEPTÍDEOS & AGONISTAS GLP-1 / GIP (METABOLISMO & REGENERAÇÃO)
  // =========================================================================
  {
    id: 'tirzepatide',
    name: 'Tirzepatida (Mounjaro)',
    category: 'peptide',
    subcategory: 'GLP-1 / GIP',
    halfLifeDays: 5.0,
    peakHours: 24,
    defaultConcentrationMgMl: 10,
    color: '#10b981',
    unit: 'mg',
    bioavailability: 0.8,
    description: 'Duplo agonista dos receptores GIP e GLP-1. Meia-vida de 5 dias, aplicação semanal.',
  },
  {
    id: 'semaglutide',
    name: 'Semaglutida (Ozempic / Wegovy)',
    category: 'peptide',
    subcategory: 'GLP-1',
    halfLifeDays: 7.0,
    peakHours: 36,
    defaultConcentrationMgMl: 2.68,
    color: '#14b8a6',
    unit: 'mg',
    bioavailability: 0.89,
    description: 'Agonista GLP-1 de longa duração com meia-vida de 7 dias, altamente eficaz no controle glicêmico e peso.',
  },
  {
    id: 'retatrutide',
    name: 'Retatrutida (Triplo Agonista GLP-1/GIP/GCGR)',
    category: 'peptide',
    subcategory: 'GLP-1 / GIP / Glucagon',
    halfLifeDays: 6.0,
    peakHours: 24,
    defaultConcentrationMgMl: 10,
    color: '#065f46',
    unit: 'mg',
    bioavailability: 0.85,
    description: 'Triplo agonista inovador com elevação do gasto energético mitocondrial e meia-vida de 6 dias.',
  },
  {
    id: 'liraglutide',
    name: 'Liraglutida (Saxenda / Victoza)',
    category: 'peptide',
    subcategory: 'GLP-1',
    halfLifeDays: 0.55, // ~13 horas
    peakHours: 11,
    defaultConcentrationMgMl: 6,
    color: '#047857',
    unit: 'mg',
    bioavailability: 0.55,
    description: 'Agonista GLP-1 de aplicação diária com meia-vida de 13 horas.',
  },
  {
    id: 'bpc_157',
    name: 'BPC-157 (Peptídeo de Reparação / Tendões)',
    category: 'peptide',
    subcategory: 'Regenerativo',
    halfLifeDays: 0.25, // ~6 horas
    peakHours: 1,
    defaultConcentrationMgMl: 5,
    color: '#2dd4bf',
    unit: 'mcg',
    bioavailability: 0.9,
    description: 'Pentadecapeptídeo gástrico potente na cicatrização de tendões, ligamentos, mucosa e articulações.',
  },
  {
    id: 'tb_500',
    name: 'TB-500 (Timosina Beta-4)',
    category: 'peptide',
    subcategory: 'Regenerativo',
    halfLifeDays: 2.0,
    peakHours: 6,
    defaultConcentrationMgMl: 5,
    color: '#34d399',
    unit: 'mg',
    bioavailability: 0.9,
    description: 'Estimulador de angiogênese e migração celular para reparação muscular e de tecidos moles.',
  },
  {
    id: 'cjc_1295_dac',
    name: 'CJC-1295 com DAC',
    category: 'peptide',
    subcategory: 'Secretagogo GH',
    halfLifeDays: 6.0,
    peakHours: 24,
    defaultConcentrationMgMl: 2,
    color: '#6ee7b7',
    unit: 'mg',
    bioavailability: 0.9,
    description: 'Análogo do GHRH com Drug Affinity Complex. Meia-vida estendida para até 6 a 8 dias.',
  },
  {
    id: 'cjc_1295_nodac',
    name: 'CJC-1295 sem DAC / Mod GRF 1-29',
    category: 'peptide',
    subcategory: 'Secretagogo GH',
    halfLifeDays: 0.05, // 30-40 min
    peakHours: 0.3,
    defaultConcentrationMgMl: 2,
    color: '#a7f3d0',
    unit: 'mcg',
    bioavailability: 0.9,
    description: 'GHRH pulsátil de ação curta, utilizado frequentemente em sinergia com a Ipamorelina.',
  },
  {
    id: 'ipamorelin',
    name: 'Ipamorelina (GHRP Seletivo)',
    category: 'peptide',
    subcategory: 'Secretagogo GH',
    halfLifeDays: 0.08, // ~2 horas
    peakHours: 0.5,
    defaultConcentrationMgMl: 2,
    color: '#059669',
    unit: 'mcg',
    bioavailability: 0.9,
    description: 'Secretagogo limpo de GH sem estimular cortisol, prolactina ou apetite excessivo.',
  },
  {
    id: 'pt_141',
    name: 'PT-141 (Bremelanotida - Libido & Desejo)',
    category: 'peptide',
    subcategory: 'Melanocortina / Libido',
    halfLifeDays: 0.12, // ~2.7 horas
    peakHours: 1,
    defaultConcentrationMgMl: 10,
    color: '#ec4899',
    unit: 'mcg',
    bioavailability: 1.0,
    description: 'Agonista dos receptores de melanocortina que atua no sistema nervoso central estimulando o desejo sexual.',
  },
  {
    id: 'melanotan_2',
    name: 'Melanotan II',
    category: 'peptide',
    subcategory: 'Melanocortina',
    halfLifeDays: 1.5,
    peakHours: 4,
    defaultConcentrationMgMl: 10,
    color: '#d97706',
    unit: 'mcg',
    bioavailability: 0.95,
    description: 'Análogo sintético do hormônio alfa-MSH para pigmentação/bronzeamento e libido.',
  },
  {
    id: 'ghk_cu',
    name: 'GHK-Cu (Peptídeo de Cobre Regenerativo)',
    category: 'peptide',
    subcategory: 'Regenerativo',
    halfLifeDays: 0.5,
    peakHours: 2,
    defaultConcentrationMgMl: 50,
    color: '#0284c7',
    unit: 'mg',
    bioavailability: 0.9,
    description: 'Peptídeo de cobre com síntese de colágeno, anti-inflamatório genômico e saúde da pele/cabelos.',
  },

  // --- BLENDS & COMBINADOS DE PEPTÍDEOS (GLOW, KLOW, SECRETAGOGOS & WOLVERINE) ---
  {
    id: 'cjc_ipamorelin_blend',
    name: 'CJC-1295 + Ipamorelina (Blend GHRP/GHRH)',
    category: 'peptide',
    subcategory: 'Blend Combinado (GH)',
    halfLifeDays: 0.1, // ~2.5 horas (sinergia pulsátil)
    peakHours: 0.5,
    defaultConcentrationMgMl: 5, // frasco 5mg/5mg (10mg total)
    color: '#059669',
    unit: 'mcg',
    bioavailability: 0.95,
    description: 'A combinação sinérgica clássica (GHRH + GHRP) para pulsos limpos de GH natural noturno sem picos de prolactina ou cortisol.',
    enabled: true,
  },
  {
    id: 'glow_blend',
    name: 'GLOW Protocol / Blend (GHK-Cu + BPC-157 + TB-500)',
    category: 'peptide',
    subcategory: 'Blend Combinado (Estética & Pele)',
    halfLifeDays: 0.7,
    peakHours: 2,
    defaultConcentrationMgMl: 70, // ex: 50mg GHK-Cu + 10mg BPC + 10mg TB-500
    color: '#06b6d4',
    unit: 'mg',
    bioavailability: 0.9,
    description: 'O famoso protocolo GLOW: estimula angiogênese, síntese de colágeno dérmico I e III, elasticidade, saúde capilar e brilho natural da pele.',
    enabled: true,
  },
  {
    id: 'klow_blend',
    name: 'KLOW Protocol / Blend (KPV + GHK-Cu + BPC-157 + TB-500)',
    category: 'peptide',
    subcategory: 'Blend Combinado (Anti-inflamatório & Pele)',
    halfLifeDays: 0.8,
    peakHours: 2.5,
    defaultConcentrationMgMl: 75,
    color: '#0ea5e9',
    unit: 'mg',
    bioavailability: 0.9,
    description: 'Protocolo KLOW avançado: adiciona o potente tripeptídeo KPV ao Glow para desinflamação profunda intestinal, clareamento da pele, acne e reparação tecidual.',
    enabled: true,
  },
  {
    id: 'wolverine_blend',
    name: 'Wolverine Blend (BPC-157 + TB-500)',
    category: 'peptide',
    subcategory: 'Blend Combinado (Regenerativo)',
    halfLifeDays: 1.2,
    peakHours: 3,
    defaultConcentrationMgMl: 10, // 5mg BPC + 5mg TB
    color: '#10b981',
    unit: 'mg',
    bioavailability: 0.9,
    description: 'A combinação regenerativa mais utilizada para recuperação acelerada de tendões, ligamentos, cirurgias e rupturas musculares.',
    enabled: true,
  },
  {
    id: 'kpv_peptide',
    name: 'KPV (Tripeptídeo Derivado do alfa-MSH)',
    category: 'peptide',
    subcategory: 'Anti-inflamatório / Gut',
    halfLifeDays: 0.25, // ~6 horas
    peakHours: 1,
    defaultConcentrationMgMl: 5,
    color: '#8b5cf6',
    unit: 'mcg',
    bioavailability: 0.9,
    description: 'Tripeptídeo antimicrobiano e anti-inflamatório potente com tropismo pelo trato gastrointestinal, mastócitos e microbiota.',
    enabled: false,
  },
  {
    id: 'tesamorelin_blend',
    name: 'Tesamorelina + Ipamorelina (Blend Metabólico)',
    category: 'peptide',
    subcategory: 'Blend Combinado (Gordura Visceral)',
    halfLifeDays: 0.15,
    peakHours: 0.5,
    defaultConcentrationMgMl: 6,
    color: '#6366f1',
    unit: 'mg',
    bioavailability: 0.9,
    description: 'Sinergia potente entre o análogo de GHRH específico para queima de gordura visceral profunda (Tesamorelina) e Ipamorelina.',
    enabled: false,
  },

  // =========================================================================
  // 3. HORMÔNIOS FEMININOS / HRT
  // =========================================================================
  {
    id: 'estradiol_valerate',
    name: 'Valerato de Estradiol (Injetável)',
    category: 'estrogen',
    subcategory: 'Estrógeno',
    halfLifeDays: 3.5,
    peakHours: 36,
    defaultConcentrationMgMl: 10,
    color: '#ec4899',
    unit: 'mg',
    bioavailability: 1.0,
    description: 'Éster injetável de 17-beta estradiol com meia-vida de 3.5 a 5 dias.',
    standardReferenceRange: { min: 50, max: 200, unit: 'pg/mL' },
  },
  {
    id: 'estradiol_cypionate',
    name: 'Cipionato de Estradiol',
    category: 'estrogen',
    subcategory: 'Estrógeno',
    halfLifeDays: 7.5,
    peakHours: 48,
    defaultConcentrationMgMl: 5,
    color: '#f43f5e',
    unit: 'mg',
    bioavailability: 1.0,
    description: 'Éster lento com curva muito estável de estradiol para reposição feminina.',
    standardReferenceRange: { min: 50, max: 200, unit: 'pg/mL' },
  },
  {
    id: 'progesterone',
    name: 'Progesterona Micronizada',
    category: 'estrogen',
    subcategory: 'Progestágeno',
    halfLifeDays: 1.2,
    peakHours: 8,
    defaultConcentrationMgMl: 50,
    color: '#fb7185',
    unit: 'mg',
    bioavailability: 0.9,
    description: 'Hormônio bioidêntico essencial para proteção endometrial, relaxamento e sono.',
    standardReferenceRange: { min: 1, max: 20, unit: 'ng/mL' },
  },

  // =========================================================================
  // 4. FERTILIDADE, TPC & PROTETORES (HPTA & ANCILLARY)
  // =========================================================================
  {
    id: 'hcg',
    name: 'hCG (Gonadotrofina Coriônica Humana)',
    category: 'fertility',
    subcategory: 'Fertilidade / HPTA',
    halfLifeDays: 1.5,
    peakHours: 16,
    defaultConcentrationMgMl: 1000,
    color: '#f59e0b',
    unit: 'IU',
    bioavailability: 0.95,
    description: 'Mimetizador de LH que mantém a produção intratesticular e fertilidade durante a TRT.',
  },
  {
    id: 'hmg',
    name: 'hMG (Menotropina / FSH + LH)',
    category: 'fertility',
    subcategory: 'Fertilidade',
    halfLifeDays: 1.5,
    peakHours: 18,
    defaultConcentrationMgMl: 75,
    color: '#d97706',
    unit: 'IU',
    bioavailability: 0.95,
    description: 'Ação direta em FSH e LH para restauração intensiva da espermatogênese.',
  },
  {
    id: 'anastrozole',
    name: 'Anastrozol (Inibidor de Aromatase Oral)',
    category: 'fertility',
    subcategory: 'Inibidor de Aromatase',
    halfLifeDays: 2.0,
    peakHours: 2,
    defaultConcentrationMgMl: 1,
    color: '#eab308',
    unit: 'mg',
    bioavailability: 0.85,
    description: 'Inibidor não-esteroide seletivo da aromatase para controle do estradiol sérico.',
  },
  {
    id: 'cabergoline',
    name: 'Cabergolina (Dostinex - Inibidor de Prolactina)',
    category: 'fertility',
    subcategory: 'Agonista Dopaminérgico',
    halfLifeDays: 3.0,
    peakHours: 3,
    defaultConcentrationMgMl: 0.5,
    color: '#a855f7',
    unit: 'mg',
    bioavailability: 0.9,
    description: 'Agonista potente dos receptores D2 de dopamina para redução rápida da prolactina sérica.',
  },
  {
    id: 'enclomiphene',
    name: 'Enclomifeno (SERM Seletivo)',
    category: 'fertility',
    subcategory: 'SERM / TPC',
    halfLifeDays: 0.42, // ~10 horas
    peakHours: 4,
    defaultConcentrationMgMl: 25,
    color: '#38bdf8',
    unit: 'mg',
    bioavailability: 0.9,
    description: 'Isômero trans purificado do clomifeno que estimula LH e FSH sem os efeitos estrogênicos do zuclomifeno.',
  },
];

export const DEFAULT_LAB_MARKERS: LabMarker[] = [
  {
    id: 'tot_t',
    name: 'Testosterona Total',
    code: 'total_t',
    category: 'hormones',
    unit: 'ng/dL',
    maleRef: { min: 300, max: 900 },
    femaleRef: { min: 15, max: 70 },
  },
  {
    id: 'free_t',
    name: 'Testosterona Livre Calculada',
    code: 'free_t',
    category: 'hormones',
    unit: 'ng/dL',
    maleRef: { min: 13, max: 40 },
    femaleRef: { min: 0.5, max: 2.5 },
  },
  {
    id: 'e2',
    name: 'Estradiol (E2)',
    code: 'e2',
    category: 'hormones',
    unit: 'pg/mL',
    maleRef: { min: 20, max: 45 },
    femaleRef: { min: 30, max: 300 },
  },
  {
    id: 'shbg',
    name: 'SHBG (Globulina Ligadora de Hormônios)',
    code: 'shbg',
    category: 'hormones',
    unit: 'nmol/L',
    maleRef: { min: 18, max: 54 },
    femaleRef: { min: 20, max: 130 },
  },
  {
    id: 'hematocrit',
    name: 'Hematócrito',
    code: 'hematocrit',
    category: 'hematology',
    unit: '%',
    maleRef: { min: 40, max: 50 },
    femaleRef: { min: 36, max: 46 },
  },
  {
    id: 'prolactin',
    name: 'Prolactina',
    code: 'prolactin',
    category: 'hormones',
    unit: 'ng/mL',
    maleRef: { min: 2.1, max: 17.7 },
    femaleRef: { min: 2.8, max: 29.2 },
  },
  {
    id: 'fasting_glucose',
    name: 'Glicemia de Jejum',
    code: 'glucose',
    category: 'metabolic',
    unit: 'mg/dL',
    maleRef: { min: 70, max: 99 },
    femaleRef: { min: 70, max: 99 },
  },
  {
    id: 'hba1c',
    name: 'Hemoglobina Glicada (HbA1c)',
    code: 'hba1c',
    category: 'metabolic',
    unit: '%',
    maleRef: { min: 4.0, max: 5.6 },
    femaleRef: { min: 4.0, max: 5.6 },
  },
  {
    id: 'alt_tgp',
    name: 'ALT / TGP (Fígado)',
    code: 'alt',
    category: 'liver_kidney',
    unit: 'U/L',
    maleRef: { min: 10, max: 40 },
    femaleRef: { min: 7, max: 35 },
  },
];

export const INJECTION_SITE_LABELS: Record<string, { label: string; area: string; side?: string }> = {
  deltoid_right: { label: 'Deltoide Direito', area: 'Ombro', side: 'Direito' },
  deltoid_left: { label: 'Deltoide Esquerdo', area: 'Ombro', side: 'Esquerdo' },
  ventroglute_right: { label: 'Ventroglúteo Direito', area: 'Quadril', side: 'Direito' },
  ventroglute_left: { label: 'Ventroglúteo Esquerdo', area: 'Quadril', side: 'Esquerdo' },
  glute_right: { label: 'Glúteo Dorsoglúteo Direito', area: 'Glúteo', side: 'Direito' },
  glute_left: { label: 'Glúteo Dorsoglúteo Esquerdo', area: 'Glúteo', side: 'Esquerdo' },
  quad_right: { label: 'Vasto Lateral Direito', area: 'Coxa', side: 'Direito' },
  quad_left: { label: 'Vasto Lateral Esquerdo', area: 'Coxa', side: 'Esquerdo' },
  abdomen_subq_right: { label: 'Abdômen SubQ Direito', area: 'Abdômen', side: 'Direito' },
  abdomen_subq_left: { label: 'Abdômen SubQ Esquerdo', area: 'Abdômen', side: 'Esquerdo' },
  love_handles_right: { label: 'Flanco / Love Handle Direito', area: 'Flanco', side: 'Direito' },
  love_handles_left: { label: 'Flanco / Love Handle Esquerdo', area: 'Flanco', side: 'Esquerdo' },
  custom: { label: 'Outro Local Customizado', area: 'Outro' },
};
